"""create initial tables

Revision ID: 632de54e226e
Revises: 
Create Date: 2026-09-14 12:07:15.027687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632de54e226e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_subject_id'), 'participants', ['subject_id'], unique=True)
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('question_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_question_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.String(length=30), nullable=False),
    sa.Column('phrase_hebrew', sa.Text(), nullable=True),
    sa.Column('gender_form', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('subquestion_number', sa.String(length=30), nullable=True),
    sa.Column('subquestion_phrase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_question_id'], ['canonical_questions.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'question_number', 'gender_form', name='uq_question_variant')
    )
    op.create_index(op.f('ix_question_variants_canonical_question_id'), 'question_variants', ['canonical_question_id'], unique=False)
    op.create_index(op.f('ix_question_variants_questionnaire_id'), 'question_variants', ['questionnaire_id'], unique=False)
    op.create_table('questionnaire_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_sessions_participant_id'), 'questionnaire_sessions', ['participant_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_sessions_questionnaire_id'), 'questionnaire_sessions', ['questionnaire_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_variant_id', sa.Integer(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_variants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_variant_id', name='uq_session_question')
    )
    op.create_index(op.f('ix_responses_question_variant_id'), 'responses', ['question_variant_id'], unique=False)
    op.create_index(op.f('ix_responses_session_id'), 'responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_session_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_question_variant_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_questionnaire_sessions_questionnaire_id'), table_name='questionnaire_sessions')
    op.drop_index(op.f('ix_questionnaire_sessions_participant_id'), table_name='questionnaire_sessions')
    op.drop_table('questionnaire_sessions')
    op.drop_index(op.f('ix_question_variants_questionnaire_id'), table_name='question_variants')
    op.drop_index(op.f('ix_question_variants_canonical_question_id'), table_name='question_variants')
    op.drop_table('question_variants')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_participants_subject_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('canonical_questions')
    # ### end Alembic commands ###
